# Generated by Django 4.0.6 on 2022-07-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_resume_title_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('Doing', 'Doing'), ('Complated', 'Complated')], default='Complated', max_length=20),
        ),
    ]
