# Generated by Django 4.0.6 on 2022-07-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_userprofile_social_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
