# Generated by Django 4.0.6 on 2022-07-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default=0.0008896797153024911, unique=True),
            preserve_default=False,
        ),
    ]
